export const posts = [
  {
    profile: require("./../assets/images/profile.png"),
    name: "John",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    type: "type/image",
    media: require("./../assets/images/cars1.jpg"),
    date: "10 March at 10:52",
  },
  {
    profile: require("./../assets/images/man.png"),
    name: "Alex",
    text: "This is a text.",
    type: "type/image",
    media: require("./../assets/images/cars2.webp"),
    date: "23 July at 18:29",
  },
  {
    profile: require("./../assets/images/man.png"),
    name: "Alex",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    type: "",
    media: "",
    date: "23 July at 18:29",
  },
  {
    profile: require("./../assets/images/profile.png"),
    name: "John",
    text: "This is a text.",
    type: "type/video",
    media: require("./../assets/videos/10-seconds-1.mp4"),
    date: "4 October at 00:44",
  },
  {
    profile: require("./../assets/images/man.png"),
    name: "Alex",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    type: "type/video",
    media: require("./../assets/videos/10-seconds-2.mp4"),
    date: "19 December at 23:14",
  },
];
