export const posts = [
  {
    profile: require("./../assets/images/profile.png"),
    name: "John",
    text: "This is a text.",
    type: "type/image",
    media: require("./../assets/images/cars1.jpg"),
    date: "10 March at 10:52",
  },
  {
    profile: require("./../assets/images/man.png"),
    name: "Alex",
    text: "This is a text.",
    type: "type/image",
    media: require("./../assets/images/cars2.webp"),
    date: "23 July at 18:29",
  },
  {
    profile: require("./../assets/images/man.png"),
    name: "Alex",
    text: "This is a text-only post. This is a text-only post. This is a text-only post. This is a text-only post. This is a text-only post.",
    type: "",
    media: "",
    date: "23 July at 18:29",
  },
  {
    profile: require("./../assets/images/profile.png"),
    name: "John",
    text: "This is a text.",
    type: "type/video",
    media: require("./../assets/videos/10-seconds-1.mp4"),
    date: "4 October at 00:44",
  },
  {
    profile: require("./../assets/images/man.png"),
    name: "Alex",
    text: "This is a text.",
    type: "type/video",
    media: require("./../assets/videos/10-seconds-2.mp4"),
    date: "19 December at 23:14",
  },
];
